apiVersion: v1
kind: Service
metadata:
  name: autoscaler-webhook-service
  labels:
    app: autoscaler-webhook
spec:
  selector:
    app: autoscaler-webhook
  ports:
    - port: 8000
      protocol: TCP
      name: https
      targetPort: autoscaler
---
apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "game-server-"
  labels:
    app: autoscaler-webhook
spec:
  container: simple-game-server
  ports:
    - name: default
      containerPort: 7654
  template:
    metadata:
      labels:
        app: autoscaler-webhook
    spec:
      containers:
        - name: autoscaler-webhook
          image: localimage/gameserver:latest
          imagePullPolicy: Never
          ports:
            - name: autoscaler
              containerPort: 8000
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
        - name: simple-game-server
          image: gcr.io/agones-images/simple-game-server:0.3
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "64Mi"
              cpu: "20m"