apiVersion: v1
kind: Service
metadata:
  name: dgs-sidecar
  labels:
    app: dgs-sidecar
spec:
  selector:
    app: dgs-sidecar
  ports:
    - port: 8000
      protocol: TCP
      name: https
      targetPort: autoscaler
---
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: dgs-sidecar
  labels:
    app: dgs-sidecar
spec:
  replicas: 2
  template:
    spec:
      container: simple-game-server
      ports:
        - name: default
          containerPort: 7654
      template:
        metadata:
          labels:
            app: dgs-sidecar
        spec:
          containers:
            - name: dgs-sidecar
              image: localimage/gameserver:latest
              imagePullPolicy: Never
              ports:
                - name: autoscaler
                  containerPort: 8000
              livenessProbe:
                httpGet:
                  scheme: HTTP
                  path: /health
                  port: 8000
                initialDelaySeconds: 3
                periodSeconds: 5
            - name: simple-game-server
              image: gcr.io/agones-images/simple-game-server:0.3
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "20m"
                limits:
                  memory: "64Mi"
                  cpu: "20m"
---
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: sidecar-autoscaler
spec:
  fleetName: dgs-sidecar
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 0
      maxReplicas: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sidecar-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: dgs-sidecar
                port:
                  number: 8000
            path: /
            pathType: Prefix