apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: dgs-sidecar
  labels:
    app: dgs-sidecar
spec:
  replicas: 2
  template:
    spec:
      container: simple-game-server
      ports:
        - name: default
          containerPort: 7654
      template:
        metadata:
          labels:
            app: dgs-sidecar
        spec:
          containers:
            - name: dgs-sidecar
              image: localimage/gameserver:latest
              imagePullPolicy: Never
              ports:
                - name: autoscaler
                  containerPort: 8000
              livenessProbe:
                httpGet:
                  scheme: HTTP
                  path: /health
                  port: 8000
                initialDelaySeconds: 3
                periodSeconds: 5
            - name: simple-game-server
              image: gcr.io/agones-images/simple-game-server:0.3
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "20m"
                limits:
                  memory: "64Mi"
                  cpu: "20m"
